image = 'flyio/log-shipper'

[metrics]
  port = 9598
  path = "/metrics"

[launcher]
name = "Log Shipper"
description = "Ship logs from Fly to other providers using NATS and Vector."
logo_url = "https://github.com/lubien/mysql-launcher/raw/main/mysql.png"
post_instructions = "Your new Log Shipper is running!"
template_description = "Here we have some vector configs and a nats client (`fly-logs`), along side a wrapper script to run it all, that will subscribe to a log stream of your organizations logs, and ship it to various providers."

[launcher.requirements.secrets.ACCESS_TOKEN]
  label = "Fly.io ACCESS_TOKEN"
  help_url = "https://fly.io/user/personal_access_tokens"
  required = true

[launcher.requirements.secrets.ORG]
  label = "Organization for environment variable `ORG`"
  type = "organization_slug"
  required = true

[launcher.requirements.secrets.SUBJECT]
  default = 'logs.>'
  help_url = 'https://github.com/superfly/fly-log-shipper#nats'
  required = true

[launcher.requirements.secrets.QUEUE]

# AWS

[launcher.requirements.secrets.AWS_ACCESS_KEY_ID]
  label = "AWS Access key with access to the log bucket"
  group = "AWS S3"
[launcher.requirements.secrets.AWS_SECRET_ACCESS_KEY]
  label = "AWS secret access key"
  group = "AWS S3"
[launcher.requirements.secrets.AWS_BUCKET]
  label = "AWS S3 bucket to store logs in"
  group = "AWS S3"
[launcher.requirements.secrets.AWS_REGION]
  label = "Region for the bucket"
  group = "AWS S3"

# Datadog

[launcher.requirements.secrets.DATADOG_API_KEY]
  label = "API key for your Datadog account"
  group = "Datadog"

# Honeycomb

[launcher.requirements.secrets.HONEYCOMB_API_KEY]
  label = "Honeycomb API key"
  group = "Honeycomb"

[launcher.requirements.secrets.HONEYCOMB_DATASET]
  label = "Honeycomb dataset"
  group = "Honeycomb"

# Humio

[launcher.requirements.secrets.HUMIO_TOKEN]
  label = "Humio token"
  group = "Humio"

# LogDNA

[launcher.requirements.secrets.LOGDNA_API_KEY]
  label = "LogDNA API key"
  group = "LogDNA"

# Logflare

[launcher.requirements.secrets.LOGFLARE_API_KEY]
  label = "Logflare ingest API key"
  group = "Logflare"
[launcher.requirements.secrets.LOGFLARE_SOURCE_TOKEN]
  label = "Logflare source token (uuid on your Logflare dashboard)"
  group = "Logflare"

# Logtail

[launcher.requirements.secrets.LOGTAIL_TOKEN]
  label = "Logtail auth token"
  group = "Logtail"

# Loki

[launcher.requirements.secrets.LOKI_URL]
  label = "Loki Endpoint"
  group = "Loki"
[launcher.requirements.secrets.LOKI_USERNAME]
  label = "Loki Username"
  group = "Loki"
[launcher.requirements.secrets.LOKI_PASSWORD]
  label = "Loki Password"
  group = "Loki"

# New Relic

[launcher.requirements.secrets.NEW_RELIC_INSERT_KEY]
  label = "New Relic Insert key"
  group = "New Relic"
[launcher.requirements.secrets.NEW_RELIC_LICENSE_KEY]
  label = "New Relic License key"
  group = "New Relic"

# Papertrail

[launcher.requirements.secrets.PAPERTRAIL_ENDPOINT]
  label = "Papertrail endpoint"
  group = "Papertrail"

# Sematext

[launcher.requirements.secrets.SEMATEXT_REGION]
  label = "Sematext region"
  group = "Sematext"
[launcher.requirements.secrets.SEMATEXT_TOKEN]
  label = "Sematext token"
  group = "Sematext"

# Uptrace

[launcher.requirements.secrets.UPTRACE_API_KEY]
  label = "Uptrace API key"
  group = "Uptrace"
[launcher.requirements.secrets.UPTRACE_PROJECT]
  label = "Uptrace project ID"
  group = "Uptrace"

# EraSearch

[launcher.requirements.secrets.ERASEARCH_URL]
  label = "EraSearch Endpoint"
  group = "EraSearch"
[launcher.requirements.secrets.ERASEARCH_AUTH]
  label = "EraSearch User"
  group = "EraSearch"
[launcher.requirements.secrets.ERASEARCH_INDEX]
  label = "EraSearch Index you want to use"
  group = "EraSearch"
